# Generated by Django 3.0.5 on 2021-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210331_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
