# Generated by Django 3.0.5 on 2021-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210331_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
