# Generated by Django 3.0.5 on 2021-03-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210331_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lession',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
