# Generated by Django 3.0.5 on 2021-04-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usercourselink'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=140)),
                ('option2', models.CharField(max_length=140)),
                ('option3', models.CharField(max_length=140)),
                ('option4', models.CharField(max_length=140)),
                ('answer', models.CharField(max_length=140)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Course')),
            ],
        ),
    ]
